### ISSUE TITLE
Arithmetic ops don't set `$of` to overflow value, but overflow state

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-vm#121]
This line https://github.com/FuelLabs/fuel-vm/blob/9f67738c684ba72c5c975808170c72c3fae5bbca/src/interpreter/executors/instruction.rs#L169 sets the `$of` register to the second return value of [`overflowing_mul`](https://doc.rust-lang.org/std/primitive.u64.html#method.overflowing_mul), which is a Boolean indicating whether an overflow occurred or not.

The specs actually say that the overflow _value_ should be placed into `$of` in the case of overflow, no simple a Boolean.

At the very least this needs to be done for add, subtract, multiply, divide, and mod. Pow can be left as-is.

**Comment by nfurfaro** [comment]
>At the very least this needs to be done for add, subtract, multiply, divide, and mod. Pow can be left as-is.

We should add the shifting ops to this list , or else change the spec.

**Comment by adlerjohn** [comment]
Right shift can't overflow. Left shift the specs will change, so I'm anticipation of that there's no need to capture the overflow value.
