### ISSUE TITLE
Have the VM update `receiptsRoot` before the script completes execution

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuel-vm#125]
It looks like we currently only set the receipts root in post script execution. The desired behaviour is probably to update that value before then so that contract methods can get it given what receipts have been generated so far.

**Comment by Voxelot** [comment]
Since this involves surgically updating the tx, I'd feel more comfortable implementing this after https://github.com/FuelLabs/fuel-specs/issues/287 is in place. How much of a blocker is this functionality @mohammadfawaz ?

**Comment by mohammadfawaz** [comment]
Not really a blocker for anything!
