### ISSUE TITLE
Refactor instruction executors

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#133]
The current instruction executors are duplicating code because the implementation is split into one storage backend that supports contract instructions and the other that won't

https://github.com/FuelLabs/fuel-vm/blob/ffaf70c6d0f7974de4bd316c1742f3698ec8c219/src/interpreter/executors/instruction.rs#L66-L848

One alternative is to use macros to avoid code duplication, but this compromises code debug since macros are usually not expanded in IDEs.

Other option is to create a single function that will match for regular instructions, and branch for contract opcodes to check the context of the execution. This is not desirable too because it would increase the computation cost of the entirety of the execution.

We need to analyze the rationale of these options and come with the best solution for this tech-debt.

**Comment by Voxelot** [comment]
what about using a bitfield on the opcode repr which is checked against the allowed list of instructions during each instruction execution?

**Comment by vlopes11** [comment]
> What about standardizing around always using InterpreterStorage, and make a concrete struct called `PredicateStorage` which just throws an interpreter error or `unimplemented!` if any of its methods are called? I don't think this would create any overhead and would keep our code pretty simple.
> 
> Then we could just use one standard instruction executor which verifies the opcodes against the allowed list when running in a predicate context. This could be optimized to use a bitfield or something similar in the future.

It does make sense since the problem revolves entirely around the storage. I'll start working on that

**Comment by Voxelot** [comment]
If we want to keep the unit type as the storage for predicates, we could even do this in `fuel-storage`

```rust

pub struct UnexpectedStorageCall;

impl<K, V> Storage<K, V> for ()
where
    V: Clone,
{
    type Error = UnexpectedStorageCall;

    fn insert(&mut self, key: &K, value: &V) -> Result<Option<V>, Self::Error> {
        return Err(UnexpectedStorageCall);
    }

    fn remove(&mut self, key: &K) -> Result<Option<V>, Self::Error> {
        return Err(UnexpectedStorageCall);
    }

    fn get<'a>(&'a self, key: &K) -> Result<Option<Cow<'a, V>>, Self::Error> {
        return Err(UnexpectedStorageCall);
    }

    fn contains_key(&self, key: &K) -> Result<bool, Self::Error> {
        return Err(UnexpectedStorageCall);
    }
}

```
