### ISSUE TITLE
Reassess the nature of the heap and `$hp`.

### ISSUE THREAD

**Issue by otrho** [FuelLabs/fuel-vm#137]
The heap and `ALOC` haven't been used at all in the Sway compiler or runtime until recently and I've noticed what I think is a slight incongruity in the way `$hp` is treated.

This is assuming what I think is the case (by testing the VM via Sway/ASM and by looking briefly at `memory.rs`) that `$hp` holds the address of the last available byte not in the heap, or the end of the memory between the stack and heap.

It is initialised to `VM_MAX_RAM - 1` which asserts this idea.  And in my experience if you try to read from `$hp` you'll get a memory overflow panic.  Reading from `$hp + 1` is fine (provided it's below `VM_MAX_RAM`).

This is a bit weird.  I think `$hp` should point to the first byte in the allocated heap.  It should therefore be initialised to `VM_MAX_RAM` -- I've suggested as much in https://github.com/FuelLabs/fuel-specs/issues/322.

Then the use of `$sp` & `CFEI`/`CFSI` and `$hp` & `ALOC` would be symmetric, just in different directions.

To allocate `16` bytes on the stack, result in `r0`:
```asm
move r0 sp
cfei 16
```
To allocate `r1` bytes on the heap, result in `r0` currently:
```asm
aloc r1
addi r0 hp 1  ; Weird. :)
```
To allocate `r1` bytes on the heap, result in `r0` after proposed adjustment:
```asm
aloc r1
move r0 hp
```

After writing all this down and reading back I know it's a pretty subtle difference and not exactly high priority, but when coming across this behaviour initially I was really confused.  Using an inclusive range for free memory isn't usually how it's done -- usually `end` will point to the first invalid item rather than the last valid one.

**Comment by adlerjohn** [comment]
I support this change.
