### ISSUE TITLE
Implement the `SMO` opcode

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuel-vm#141]
This is needed to implement the  L1 <=> L2 Bridge, specifically for the `L2ERC20Gateway` contract, but most likely in more places as well.
cc @vlopes11

**Comment by rakita** [comment]
related to: https://github.com/FuelLabs/fuel-core/issues/401

**Comment by Voxelot** [comment]
blocked by https://github.com/FuelLabs/fuel-tx/issues/145

**Comment by adlerjohn** [comment]
Closed by #159
