### ISSUE TITLE
Ownership check shouldn't fail for empty memory range

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#147]
For a range `$m[x, 0]`, the ownership check fails here since `x < x + 0` will never be met

https://github.com/FuelLabs/fuel-vm/blob/52cbe36086cd09e2bbc0e89eb8009f272bd48850/src/interpreter/memory.rs#L230

Technically speaking, this isn't an illegal range, but it might lead to undefined behavior if used in some opcodes.

Example: `mcp $rA $rA $zero`

If this is considered a legal range, then we will

https://github.com/FuelLabs/fuel-vm/blob/52cbe36086cd09e2bbc0e89eb8009f272bd48850/src/interpreter/memory.rs#L395

It clearly violates the constraints of [std](https://doc.rust-lang.org/std/index.html)::[ptr](https://doc.rust-lang.org/std/ptr/index.html)::[copy_nonoverlapping](https://doc.rust-lang.org/std/ptr/fn.copy_nonoverlapping.html#), but then the compiler might be smart enough to translate this into `noop` since the length is `0`.

We could alternatively add an extra check before any non-overlapping copy, but then we are increasing the execution cost as result of an edge case that should be `NOOP`

**Comment by vlopes11** [comment]
Update: the example is illegal since `mcp` shouldn't overlap.

https://github.com/FuelLabs/fuel-specs/blob/fcfe18a585a465c750fd939b0fd85a30255d6c00/specs/vm/instruction_set.md?plain=1#L954

Maybe there isn't a single legal case for such ranges?

**Comment by adlerjohn** [comment]
This isn't so much a bug as much as the specification doesn't allow for this behavior. I don't think it's necessarily desirable to add for the aforementioned reasons, namely performance.
