### ISSUE TITLE
Logarithm instruction `mlog` needs discussion

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuel-vm#150]
I would expect that `assert(1000.logarithm(10) == 3);` would pass, but it does not.
Instead, logging `1000.logarithm(10)` returns `2`,

The testing I've done uses this implementation in sway:
```
impl Logarithm for u64 {
    fn logarithm(self, base: Self) -> Self {
        asm(r1: self, r2: base, r3) {
            mlog r3 r1 r2;
            r3: Self
        }
    }
}
```
Note that other cases are working as expected, i.e:
```
assert(4.logarithm(2) == 2);
assert(16.logarithm(2) == 4);
assert(9.logarithm(3) == 2);
assert(100.logarithm(10) == 2);
```

**Comment by vlopes11** [comment]
Its a problem in Rust stdlib:

https://gist.github.com/rust-play/b3ef53348c01c391a677f9bfe57aff41

As I see, we have two alternatives

- restrict the functionality domain to provide only log for bases `2` and `10` to not compromise correctness
- `round` instead of `floor`

**Comment by Voxelot** [comment]
We should find a solution that avoids f64 at all possible due to imprecision of floating point numbers. While epsilon fixes one edge case, there may be others it doesn't fix due to f64 precision.

**Comment by ControlCplusControlV** [comment]
I do want to add context that one major use for `MLOG` is computing ticks in Concentrated Liquidity, where `log2 (number)` is computed to find an integer tick. [Can be seen here](https://github.com/sway-libs/amm/blob/main/src/concentrated/tick_math.sw#L218 ), so getting closer to a real integer rather than just cutting down could be very helpful for that usecase

**Comment by Dentosal** [comment]
I think the best solution would be to use the unstable `#![feature(int_log)]` Rust feature, see [tracking issue 70887](https://github.com/rust-lang/rust/issues/70887). It's nearing it's final comment period with no unresolved issues, and I do not expect any breaking changes to it anymore. The functionality is available on nightly. If we do not want to depend on nightly, the implementation can be copied from [the Rust corelib source code](https://github.com/rust-lang/rust/blob/415d8fcc3e17f8c1324a81cf2aa7127b4fcfa32e/library/core/src/num/uint_macros.rs#L774).

The implementation behaves correctly for our use cases. For instance, it gives `1000u64.checked_ilog(10) == Some(3)` while still returning zero for log<sub>{3,4,5,...}</sub>(2).  The performance is reasonable, although likely slower than the floating point implementation.

The impl boils down to some sanity checks for values, and then

```rust
let mut n = 0;
let mut r = exp;
while r >= base {
    r /= base;
    n += 1;
}
return n;
```

As we can see, worst case would likely be some small-but-hard-to-divide-with number. In the worst theoretical case, i.e. when division takes constant cycles, base is `2` and exp is `u64::MAX`, this still takes only 64 loops, the whole function taking estimated 2<sup>11</sup> = 2048 cpu cycles. Compared to `FYL2X`  instruction used by the floating point, I'd approximate this is around one magnitude slower (looking at the [Agner Fog instruction tables](https://www.agner.org/optimize/instruction_tables.pdf) for the fp instruction timings). This should still mean at most 1 microsecond per MLOG instruction.

## Benchmark

The ilog-based code about a magnitude is slower for small base and big exponent, while float+round is a magnitude slower for small base and large exponent. The worst case performance is approximately equal for both methods. Of course we could check for power-of-two bases and compute those significantly faster.

### Results

Running with `cargo run --release` on a M1 macbook air.

Exponent             | Base                 | ilog timing          | float timing         | ilog/float timing
--------------------:|---------------------:|---------------------:|---------------------:|---------------------
2                    | 2                    |            911.018ms |             58.575ms |          15.5530
2                    | 3                    |            538.124ms |             55.586ms |           9.6809
2                    | 10                   |            166.287ms |             54.922ms |           3.0277
2                    | 16                   |            100.237ms |             56.743ms |           1.7665
2                    | 1337                 |             37.809ms |             54.720ms |           0.6910
2                    | 2147483647           |             13.049ms |             64.277ms |           0.2030
3                    | 2                    |            867.192ms |             57.912ms |          14.9743
3                    | 3                    |            534.066ms |             55.898ms |           9.5543
3                    | 10                   |            166.196ms |             55.769ms |           2.9801
3                    | 16                   |            100.663ms |             58.440ms |           1.7225
3                    | 1337                 |             37.815ms |             55.141ms |           0.6858
3                    | 2147483647           |             12.881ms |             55.357ms |           0.2327
1000                 | 2                    |            866.932ms |             59.099ms |          14.6694
1000                 | 3                    |            534.219ms |             54.961ms |           9.7201
1000                 | 10                   |            166.261ms |             54.950ms |           3.0257
1000                 | 16                   |            100.343ms |             59.373ms |           1.6900
1000                 | 1337                 |             37.808ms |             67.225ms |           0.5624
1000                 | 2147483647           |             13.154ms |             55.114ms |           0.2387
1337                 | 2                    |            869.321ms |             56.065ms |          15.5059
1337                 | 3                    |            534.129ms |             56.186ms |           9.5064
1337                 | 10                   |            170.266ms |             55.522ms |           3.0666
1337                 | 16                   |            100.208ms |             54.956ms |           1.8234
1337                 | 1337                 |             37.844ms |             61.664ms |           0.6137
1337                 | 2147483647           |             13.085ms |             58.999ms |           0.2218
2147483647           | 2                    |            867.504ms |             55.493ms |          15.6330
2147483647           | 3                    |            538.438ms |             54.950ms |           9.7987
2147483647           | 10                   |            166.158ms |             61.173ms |           2.7162
2147483647           | 16                   |             99.996ms |             65.391ms |           1.5292
2147483647           | 1337                 |             37.844ms |             58.653ms |           0.6452
2147483647           | 2147483647           |             13.033ms |             58.742ms |           0.2219
18446744073709551615 | 2                    |            869.497ms |             66.730ms |          13.0303
18446744073709551615 | 3                    |            552.618ms |             65.973ms |           8.3764
18446744073709551615 | 10                   |            166.769ms |             66.366ms |           2.5129
18446744073709551615 | 16                   |            101.139ms |             55.018ms |           1.8383
18446744073709551615 | 1337                 |             37.947ms |             54.875ms |           0.6915
18446744073709551615 | 2147483647           |             13.201ms |             55.295ms |           0.2387

### Code

```rust
#![feature(test, int_log)]

extern crate test;

use std::time::Instant;

const ROUNDS: usize = 10_000_000;

fn main() {
    print!("Exponent             | ");
    print!("Base                 | ");
    print!("ilog timing          | ");
    print!("float timing         | ");
    println!("ilog/float timing");
    println!("{}", "---------------------:|".repeat(5).strip_prefix("-").unwrap().strip_suffix(":|").unwrap());

    for exp in [2, 3, 1_000, 1337, 2_147_483_647, u64::MAX] {
        for base in [2, 3, 10, 16, 1337, 2_147_483_647] {
            let a_start = Instant::now();
            for _ in 0..ROUNDS {
                let b: u64 = test::black_box(u64::MAX);
                let c: u64 = test::black_box(base);
        
                test::black_box(b.checked_ilog(c));
            }
        
            let a_duration = a_start.elapsed();
        
            let b_start = Instant::now();
            for _ in 0..ROUNDS {
                let b: u64 = test::black_box(u64::MAX);
                let c: u64 = test::black_box(base);
        
                test::black_box((b as f64).log(c as f64).floor());
            }
        
        
            let b_duration = b_start.elapsed();
            

            let ratio = (a_duration.as_micros() as f64) / (b_duration.as_micros() as f64);

            println!("{exp:<20} | {base:<20} | {a_duration:>20.3?} | {b_duration:>20.3?} | {ratio:>16.4}");
        }
    }
}
```

## Alternatives

If this is not sufficiently fast and we still want the correct solution, maybe we could implement some proven-efficient algorithm, e.g. this one https://hal.archives-ouvertes.fr/hal-01227877/document

**Comment by Voxelot** [comment]
Taking a performance hit here is acceptable since precision errors can accumulate and this may be used in financial contexts. We must prioritize numerical precision and correctness over performance.

Taking a dependency on nightly will break too much tooling and external processes, and since we don't expect ilog to stay in nightly long I don't think it's worth the lift to make the process change now. Given it is likely temporary, I'm ok with copying the Rust impl for now until it has stabilized.

Regarding alternate algorithms, extra perf is always nice but let's get a vetted implementation in place first and then optimize later.
