### ISSUE TITLE
Remove `height` argument from initialization

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#156]
Height is taken as argument here

https://github.com/FuelLabs/fuel-vm/blob/70243e4da9acf1b03f8d4f34ccdf129e3b20c4b0/src/interpreter/initialization.rs#L17

When it should be fetched from the storage

https://github.com/FuelLabs/fuel-vm/blob/70243e4da9acf1b03f8d4f34ccdf129e3b20c4b0/src/storage/interpreter.rs#L12-L25

**Comment by Voxelot** [comment]
@vlopes11 is this completed?
