### ISSUE TITLE
Use parameter to define base asset ID

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#164]
Orthogonal to this PR, but I'm thinking the base asset's ID should be a parameter in the VM. It's not necessarily guaranteed to be `AssetId::default()` always. Both the specs and the implementation should be modular in this regard. Can you file an issue to track changing?

_Originally posted by @adlerjohn in https://github.com/FuelLabs/fuel-vm/pull/159#discussion_r912495266_

**Comment by Voxelot** [comment]
I think this should be added to the [`ConsensusParams`](https://github.com/FuelLabs/fuel-tx/blob/master/src/transaction/consensus_parameters.rs#L8) Struct in fuel-tx
