### ISSUE TITLE
Add message predicate verification tests

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#181]
lgtm, although we should probably have a test to verify MessagePredicate inputs are actually verified

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-vm/pull/180#pullrequestreview-1059099267_

**Comment by xgreenx** [comment]
I think that it is already solved in the latest codebase. But it would be nice it someone will double check that @Dentosal <3
