### ISSUE TITLE
Add read_as and write to Interpreter

### ISSUE THREAD

**Issue by ghost** [FuelLabs/fuel-vm#222]
We have duplicated this logic in several places.

We can add to `Interpreter` two new methods, `read_as` and `write`.

`read_as` will be generic and accept types that implement the `as_ref_unchecked` method(we need to move this method to the trait).

You will be able to write code like:

```rust
let signature: Signature = self.read_as(b)?;
let message: Message = self.read_as(c)?;
```

_Originally posted by @xgreenx in https://github.com/FuelLabs/fuel-vm/pull/203#discussion_r973288071_

**Comment by xgreenx** [comment]
Is not actual anymore
