### ISSUE TITLE
Error propagation

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#230]
In order to deliver more & fast, `std::io::Error` was abused due to its broad compatibility with different crates + downstream + upstream usage, ranging from serde serialization to rocksdb storage operations

We need to unify the error scheme of the stack, keeping in mind that we have two classes of errors:

- recoverable: anything that derives from a script that cannot cause an execution halt and should end charging the consumed gas from the user
- unrecoverable: anything that goes beyond the static transactions such as OS errors (out of memory, etc) or storage errors. In these cases, gas can't be charged from the user, for valid transactions

**Comment by Dentosal** [comment]
This will be likely fixed in https://github.com/FuelLabs/fuel-vm/pull/582, as we cannot use `std::io::Error` anymore.
