### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#231]
In order to make the VM available to Sway+Compiler ASAP, the tests were created directly as integrated, skipping the unit testing part.

In the integrated tests, we have well-formed scripts with storages that will simulate a compiled transaction - and execute it.

However, we also need unit tests to cover the internal functions of the VM, even without the runtime setup (tx + storage + memory client).

**Comment by Dentosal** [comment]
Closing as this is too broad. All opcodes as well as most internal functions now have proper unit tests.
