### ISSUE TITLE
MROO has float rounding issues

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-vm#260]
Similarly to the MLOG issues discussed in https://github.com/FuelLabs/fuel-vm/issues/150, MROO also has floating point rounding issues. This is the only location of the vm still using floats.

For instance, calling MROO with values `mroo(647214625, 3)`, i.e. cube root of 647214625, gives 864.9999999999997 in floating point, while 865**3 == 647214625.

I'll investigate the performance impact of handling this with integer-only operations.

**Comment by Dentosal** [comment]
I benchmarked the generally fast [`num-integer::Roots :: nth-root`](https://docs.rs/num-integer/latest/num_integer/trait.Roots.html) and my error correcting floating point solution seen below.

While the num-integer is a bit faster on the average case compared to the current floating point solution, it has some really bad edge cases. Benchmarks found over 70x runtime cases and I suspect even 100x would be possible. See `mroo(4294967296, 21)` for an example of this.

The custom implementation seen below performs acceptably. For non-interesting inputs it's four times faster. Even in the worst case it only takes around three times longer than the current version. 

## Custom error correction

```rust
fn custom(target: u64, nth_root: u32) -> u64 {
    if nth_root == 0 {
        panic!();
    }

    if nth_root == 1  || target <= 1 {
        return target;
    }

    if nth_root > 64 {
        // for any n>1, n**64 can never fit into u64
        return 1;
    }

    if nth_root as u64  >= target {
        return 1;
    }

    let guess = (target as f64).powf((nth_root as f64).recip()) as u64;

    let Some(guess_t) = guess.checked_pow(nth_root) else {
        // guess**nth_root >= 2**64 and target < 2**64
        return guess - 1;
    };

    if guess_t == target {
        return guess; // Perfect
    }

    debug_assert!(guess_t < target);

    // (guess+1)**nth_root
    let Some(guess_plus1_t) = (guess + 1).checked_pow(nth_root) else {
        // (guess+1)**nth_root >= 2**64 and target < 2**64
        return guess;
    };

    if guess_plus1_t == target {
        return guess + 1; // Perfect
    }

    guess
}
```

## Results

`cargo run --release`

Exponent             | Base                 | iroot timing         | custom-impl timing   | float timing         | iroot/float timing   |custom/float timing
--------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------:|---------------------
2                    | 2                    |             62.862ms |             13.808ms|             42.477ms |           1.4799 |           0.3251
2                    | 3                    |             51.666ms |             10.932ms|             39.968ms |           1.2927 |           0.2735
2                    | 4                    |             31.477ms |             10.931ms|             40.065ms |           0.7856 |           0.2728
2                    | 5                    |             31.456ms |             10.959ms|             40.145ms |           0.7835 |           0.2730
2                    | 6                    |             31.549ms |             10.998ms|             40.786ms |           0.7735 |           0.2696
2                    | 7                    |             31.567ms |             10.951ms|             40.788ms |           0.7739 |           0.2685
2                    | 10                   |             31.602ms |             10.928ms|             40.723ms |           0.7760 |           0.2684
2                    | 16                   |             31.585ms |             10.940ms|             40.834ms |           0.7735 |           0.2679
2                    | 21                   |             31.490ms |             10.956ms|             40.657ms |           0.7745 |           0.2695
2                    | 30                   |             31.515ms |             10.931ms|             40.763ms |           0.7731 |           0.2682
2                    | 100                  |             31.519ms |              9.370ms|             40.721ms |           0.7740 |           0.2301
2                    | 1337                 |             31.966ms |              9.380ms|             40.769ms |           0.7841 |           0.2301
2                    | 2147483647           |             31.539ms |              9.387ms|             40.746ms |           0.7741 |           0.2304
3                    | 2                    |             31.883ms |            110.171ms|             93.052ms |           0.3426 |           1.1840
3                    | 3                    |             51.669ms |             10.931ms|             92.940ms |           0.5559 |           0.1176
3                    | 4                    |             31.511ms |             10.929ms|             93.080ms |           0.3385 |           0.1174
3                    | 5                    |             31.540ms |             10.935ms|             93.202ms |           0.3384 |           0.1173
3                    | 6                    |             31.490ms |             10.931ms|             93.478ms |           0.3369 |           0.1169
3                    | 7                    |             31.494ms |             10.928ms|             93.442ms |           0.3370 |           0.1169
3                    | 10                   |             31.582ms |             10.931ms|             93.140ms |           0.3391 |           0.1174
3                    | 16                   |             31.471ms |             10.931ms|             93.180ms |           0.3377 |           0.1173
3                    | 21                   |             31.507ms |             11.040ms|             93.381ms |           0.3374 |           0.1182
3                    | 30                   |             31.543ms |             10.929ms|             93.272ms |           0.3382 |           0.1172
3                    | 100                  |             31.456ms |              9.371ms|             93.485ms |           0.3365 |           0.1002
3                    | 1337                 |             31.490ms |              9.371ms|             93.245ms |           0.3377 |           0.1005
3                    | 2147483647           |             31.484ms |              9.444ms|             93.684ms |           0.3361 |           0.1008
4                    | 2                    |             31.929ms |             56.816ms|             40.322ms |           0.7918 |           1.4091
4                    | 3                    |             51.755ms |             75.973ms|             40.419ms |           1.2804 |           1.8796
4                    | 4                    |             31.546ms |             10.935ms|             40.680ms |           0.7755 |           0.2688
4                    | 5                    |             31.558ms |             11.007ms|             40.744ms |           0.7745 |           0.2701
4                    | 6                    |             31.644ms |             10.931ms|             40.650ms |           0.7784 |           0.2689
4                    | 7                    |             31.584ms |             10.931ms|             40.699ms |           0.7760 |           0.2686
4                    | 10                   |             31.597ms |             10.929ms|             40.792ms |           0.7746 |           0.2679
4                    | 16                   |             31.656ms |             10.928ms|             40.758ms |           0.7767 |           0.2681
4                    | 21                   |             31.537ms |             10.928ms|             40.662ms |           0.7756 |           0.2688
4                    | 30                   |             31.584ms |             10.990ms|             40.839ms |           0.7734 |           0.2691
4                    | 100                  |             31.550ms |              9.617ms|             40.836ms |           0.7726 |           0.2355
4                    | 1337                 |             31.530ms |              9.485ms|             40.767ms |           0.7734 |           0.2326
4                    | 2147483647           |             31.571ms |              9.469ms|             40.827ms |           0.7733 |           0.2319
5                    | 2                    |             31.986ms |            111.307ms|             94.358ms |           0.3390 |           1.1796
5                    | 3                    |             51.660ms |            114.764ms|             93.550ms |           0.5522 |           1.2268
5                    | 4                    |             31.538ms |            118.818ms|             94.042ms |           0.3354 |           1.2635
5                    | 5                    |             31.470ms |             10.978ms|             93.933ms |           0.3350 |           0.1169
5                    | 6                    |             31.471ms |             11.000ms|             93.792ms |           0.3355 |           0.1173
5                    | 7                    |             31.478ms |             10.931ms|             94.022ms |           0.3348 |           0.1163
5                    | 10                   |             31.477ms |             11.039ms|             94.135ms |           0.3344 |           0.1173
5                    | 16                   |             31.499ms |             11.113ms|             94.252ms |           0.3342 |           0.1179
5                    | 21                   |             31.499ms |             11.009ms|             94.478ms |           0.3334 |           0.1165
5                    | 30                   |             31.576ms |             11.030ms|             94.001ms |           0.3359 |           0.1173
5                    | 100                  |             31.476ms |              9.411ms|             94.002ms |           0.3348 |           0.1001
5                    | 1337                 |             31.471ms |              9.508ms|             93.409ms |           0.3369 |           0.1018
5                    | 2147483647           |             31.464ms |              9.490ms|             93.984ms |           0.3348 |           0.1010
6                    | 2                    |             31.916ms |            111.215ms|             94.615ms |           0.3373 |           1.1754
6                    | 3                    |             51.649ms |            115.596ms|             94.833ms |           0.5446 |           1.2189
6                    | 4                    |             31.536ms |            119.392ms|             93.329ms |           0.3379 |           1.2793
6                    | 5                    |             31.478ms |            124.347ms|             92.891ms |           0.3389 |           1.3386
6                    | 6                    |             31.464ms |             10.959ms|             92.922ms |           0.3386 |           0.1179
6                    | 7                    |             31.535ms |             10.928ms|             92.930ms |           0.3393 |           0.1176
6                    | 10                   |             31.502ms |             10.928ms|             92.948ms |           0.3389 |           0.1176
6                    | 16                   |             31.452ms |             10.928ms|             92.877ms |           0.3386 |           0.1177
6                    | 21                   |             31.510ms |             10.928ms|             92.935ms |           0.3390 |           0.1176
6                    | 30                   |             31.512ms |             10.931ms|             93.387ms |           0.3374 |           0.1171
6                    | 100                  |             31.480ms |              9.368ms|             92.983ms |           0.3386 |           0.1007
6                    | 1337                 |             31.483ms |              9.368ms|             92.984ms |           0.3386 |           0.1007
6                    | 2147483647           |             31.490ms |              9.400ms|             93.462ms |           0.3369 |           0.1006
7                    | 2                    |             31.959ms |            111.535ms|             94.811ms |           0.3371 |           1.1764
7                    | 3                    |             51.683ms |            115.763ms|             94.802ms |           0.5452 |           1.2211
7                    | 4                    |             31.595ms |            119.863ms|             94.701ms |           0.3336 |           1.2657
7                    | 5                    |             31.489ms |            125.266ms|             94.733ms |           0.3324 |           1.3223
7                    | 6                    |             31.488ms |            125.098ms|             94.414ms |           0.3335 |           1.3250
7                    | 7                    |             31.512ms |             10.931ms|             92.937ms |           0.3391 |           0.1176
7                    | 10                   |             31.500ms |             10.940ms|             94.467ms |           0.3335 |           0.1158
7                    | 16                   |             31.715ms |             11.145ms|             92.978ms |           0.3411 |           0.1199
7                    | 21                   |             31.521ms |             10.931ms|             92.968ms |           0.3391 |           0.1176
7                    | 30                   |             31.511ms |             10.931ms|             92.959ms |           0.3390 |           0.1176
7                    | 100                  |             31.491ms |              9.371ms|             92.973ms |           0.3387 |           0.1008
7                    | 1337                 |             31.453ms |              9.371ms|             92.967ms |           0.3383 |           0.1008
7                    | 2147483647           |             31.486ms |              9.374ms|             92.973ms |           0.3387 |           0.1008
16                   | 2                    |             31.934ms |             55.853ms|             39.610ms |           0.8062 |           1.4100
16                   | 3                    |             80.274ms |             76.089ms|             39.568ms |           2.0288 |           1.9230
16                   | 4                    |             37.489ms |             63.243ms|             39.563ms |           0.9476 |           1.5985
16                   | 5                    |             31.506ms |             83.430ms|             39.628ms |           0.7951 |           2.1054
16                   | 6                    |             31.452ms |             82.724ms|             39.682ms |           0.7926 |           2.0847
16                   | 7                    |             31.489ms |             94.276ms|             39.604ms |           0.7951 |           2.3805
16                   | 10                   |             31.457ms |             98.580ms|             39.619ms |           0.7940 |           2.4882
16                   | 16                   |             31.973ms |             10.928ms|             40.126ms |           0.7968 |           0.2723
16                   | 21                   |             31.474ms |             10.926ms|             40.395ms |           0.7792 |           0.2705
16                   | 30                   |             31.496ms |             10.960ms|             39.991ms |           0.7876 |           0.2740
16                   | 100                  |             31.505ms |              9.366ms|             40.095ms |           0.7857 |           0.2336
16                   | 1337                 |             31.516ms |              9.368ms|             40.091ms |           0.7861 |           0.2336
16                   | 2147483647           |             31.490ms |              9.368ms|             40.110ms |           0.7851 |           0.2335
100                  | 2                    |             31.920ms |            103.334ms|             92.946ms |           0.3434 |           1.1118
100                  | 3                    |             79.576ms |            113.976ms|             92.995ms |           0.8557 |           1.2256
100                  | 4                    |             59.685ms |            117.845ms|             93.030ms |           0.6416 |           1.2668
100                  | 5                    |             83.828ms |            124.395ms|             92.954ms |           0.9018 |           1.3382
100                  | 6                    |             46.840ms |            124.250ms|             93.102ms |           0.5031 |           1.3346
100                  | 7                    |             31.446ms |            133.940ms|             92.934ms |           0.3384 |           1.4412
100                  | 10                   |             31.478ms |            136.784ms|             92.981ms |           0.3385 |           1.4711
100                  | 16                   |             31.506ms |            145.101ms|             92.996ms |           0.3388 |           1.5603
100                  | 21                   |             31.457ms |            155.766ms|             93.011ms |           0.3382 |           1.6747
100                  | 30                   |             31.499ms |            202.166ms|             93.244ms |           0.3378 |           2.1681
100                  | 100                  |             31.500ms |              9.387ms|             92.964ms |           0.3388 |           0.1010
100                  | 1337                 |             31.496ms |              9.380ms|             92.942ms |           0.3389 |           0.1009
100                  | 2147483647           |             31.483ms |              9.371ms|             93.222ms |           0.3377 |           0.1005
1000                 | 2                    |             31.896ms |            109.379ms|             92.950ms |           0.3431 |           1.1767
1000                 | 3                    |             83.531ms |            114.225ms|             92.920ms |           0.8989 |           1.2293
1000                 | 4                    |             90.652ms |            117.805ms|             93.420ms |           0.9704 |           1.2610
1000                 | 5                    |             56.167ms |            124.405ms|             92.935ms |           0.6044 |           1.3386
1000                 | 6                    |             78.067ms |            124.030ms|             93.089ms |           0.8386 |           1.3324
1000                 | 7                    |            109.635ms |            131.739ms|             93.071ms |           1.1780 |           1.4155
1000                 | 10                   |             31.490ms |            136.386ms|             92.978ms |           0.3387 |           1.4669
1000                 | 16                   |             31.483ms |            143.226ms|             92.901ms |           0.3389 |           1.5417
1000                 | 21                   |             31.455ms |            155.772ms|             92.905ms |           0.3386 |           1.6767
1000                 | 30                   |             31.487ms |            203.368ms|             92.943ms |           0.3388 |           2.1881
1000                 | 100                  |             31.500ms |              9.371ms|             92.958ms |           0.3389 |           0.1008
1000                 | 1337                 |             31.455ms |              9.364ms|             92.915ms |           0.3385 |           0.1008
1000                 | 2147483647           |             31.519ms |              9.371ms|             93.044ms |           0.3387 |           0.1007
1337                 | 2                    |             31.967ms |            109.455ms|             92.947ms |           0.3439 |           1.1776
1337                 | 3                    |             83.549ms |            114.429ms|             92.985ms |           0.8985 |           1.2306
1337                 | 4                    |             59.688ms |            117.475ms|             92.962ms |           0.6421 |           1.2637
1337                 | 5                    |             37.169ms |            124.386ms|             93.017ms |           0.3996 |           1.3372
1337                 | 6                    |             78.153ms |            124.152ms|             93.167ms |           0.8389 |           1.3326
1337                 | 7                    |            109.363ms |            131.806ms|             92.965ms |           1.1764 |           1.4178
1337                 | 10                   |             62.449ms |            136.391ms|             92.972ms |           0.6717 |           1.4670
1337                 | 16                   |             31.453ms |            143.358ms|             93.040ms |           0.3381 |           1.5408
1337                 | 21                   |             31.455ms |            156.198ms|             92.949ms |           0.3384 |           1.6805
1337                 | 30                   |             31.461ms |            202.110ms|             92.999ms |           0.3383 |           2.1733
1337                 | 100                  |             31.452ms |              9.372ms|             92.980ms |           0.3383 |           0.1008
1337                 | 1337                 |             31.503ms |              9.371ms|             92.946ms |           0.3389 |           0.1008
1337                 | 2147483647           |             31.457ms |              9.371ms|             94.448ms |           0.3331 |           0.0992
2147483647           | 2                    |             32.416ms |            111.996ms|             94.702ms |           0.3423 |           1.1826
2147483647           | 3                    |             89.098ms |            115.907ms|             94.733ms |           0.9405 |           1.2235
2147483647           | 4                    |             91.624ms |            119.709ms|             94.732ms |           0.9672 |           1.2637
2147483647           | 5                    |             84.880ms |            126.648ms|             95.158ms |           0.8920 |           1.3309
2147483647           | 6                    |            114.436ms |            126.172ms|             94.742ms |           1.2079 |           1.3318
2147483647           | 7                    |            153.060ms |            133.802ms|             94.705ms |           1.6162 |           1.4128
2147483647           | 10                   |             63.368ms |            138.705ms|             95.182ms |           0.6658 |           1.4573
2147483647           | 16                   |            101.562ms |            143.270ms|             92.989ms |           1.0922 |           1.5407
2147483647           | 21                   |            149.922ms |            156.242ms|             93.078ms |           1.6107 |           1.6786
2147483647           | 30                   |             58.058ms |            202.380ms|             92.973ms |           0.6245 |           2.1768
2147483647           | 100                  |             31.446ms |              9.365ms|             92.874ms |           0.3386 |           0.1008
2147483647           | 1337                 |             31.443ms |              9.365ms|             92.869ms |           0.3386 |           0.1008
2147483647           | 2147483647           |             31.443ms |              9.365ms|             92.961ms |           0.3382 |           0.1007
4294967296           | 2                    |             31.918ms |             55.889ms|             39.714ms |           0.8037 |           1.4073
4294967296           | 3                    |             69.820ms |             76.010ms|             39.649ms |           1.7610 |           1.9171
4294967296           | 4                    |            135.798ms |             63.052ms|             39.967ms |           3.3978 |           1.5776
4294967296           | 5                    |            110.035ms |             83.384ms|             39.552ms |           2.7821 |           2.1082
4294967296           | 6                    |            114.393ms |             82.712ms|             39.502ms |           2.8959 |           2.0938
4294967296           | 7                    |            115.661ms |             94.300ms|             39.589ms |           2.9215 |           2.3819
4294967296           | 10                   |            120.652ms |             98.572ms|             39.892ms |           3.0245 |           2.4710
4294967296           | 16                   |            128.231ms |             74.846ms|             39.580ms |           3.2398 |           1.8910
4294967296           | 21                   |               2.753s |            118.817ms|             39.616ms |          69.4884 |           2.9992
4294967296           | 30                   |            138.361ms |            152.491ms|             39.605ms |           3.4935 |           3.8503
4294967296           | 100                  |             31.536ms |              9.371ms|             40.110ms |           0.7862 |           0.2336
4294967296           | 1337                 |             31.457ms |              9.368ms|             40.003ms |           0.7864 |           0.2342
4294967296           | 2147483647           |             31.492ms |              9.371ms|             39.983ms |           0.7877 |           0.2344
18446744073709551615 | 2                    |             31.866ms |             50.580ms|             39.598ms |           0.8047 |           1.2773
18446744073709551615 | 3                    |             69.473ms |             74.197ms|             39.635ms |           1.7528 |           1.8720
18446744073709551615 | 4                    |            186.768ms |             55.997ms|             39.590ms |           4.7176 |           1.4144
18446744073709551615 | 5                    |            110.581ms |             81.634ms|             39.777ms |           2.7800 |           2.0523
18446744073709551615 | 6                    |            114.453ms |             81.519ms|             39.740ms |           2.8800 |           2.0513
18446744073709551615 | 7                    |            115.899ms |             92.112ms|             39.592ms |           2.9273 |           2.3265
18446744073709551615 | 10                   |            120.429ms |             94.419ms|             39.558ms |           3.0444 |           2.3869
18446744073709551615 | 16                   |            303.509ms |             68.955ms|             39.750ms |           7.6354 |           1.7347
18446744073709551615 | 21                   |            123.149ms |            111.545ms|             39.587ms |           3.1109 |           2.8178
18446744073709551615 | 30                   |            303.548ms |            126.851ms|             39.620ms |           7.6617 |           3.2017
18446744073709551615 | 100                  |             31.494ms |              9.371ms|             39.991ms |           0.7875 |           0.2343
18446744073709551615 | 1337                 |             31.490ms |              9.393ms|             40.134ms |           0.7846 |           0.2340
18446744073709551615 | 2147483647           |             31.510ms |              9.380ms|             39.981ms |           0.7881 |           0.2346

**Comment by freesig** [comment]
Hey @Dentosal any idea what the main usage of time is on your benchmarks? Would be interesting to get some flamegraphs to compare the two.
You can easily create them with [cargo-flamegraph](https://github.com/flamegraph-rs/flamegraph)

**Comment by Dentosal** [comment]
I can look into it, but flamegraphs are not going to help here, since the work is completely CPU-bound and inlined into a single function, `<u64 as num_integer::roots::Roots>::nth_root::go`. That in turn uses Newton's method, which might take a long time to converge on some inputs. The problematic code is [this closure](https://docs.rs/num-integer/latest/src/num_integer/roots.rs.html#265), which is iterated way too many times. This is due to Newton's method converging quite slowly here. My code doesn't suffer from the same issue, as it doesn't have to support 128bit inputs.

**Comment by Dentosal** [comment]
My older implementation had a bug that it would produce incorrect values for some weird cases with big numbers like nroot(15455138536657945190, 2) and nroot(11875230360893570326, 27).  These have now been fixed and updated in the earlier comment along with the benchmark.

Unfortunately I'm unable to prove that the error is always small enough that my code is correct. However, I'm rather confident that it is. I have ran following tests for it, verifying it against the num_integer crate:
* For all cases where 2 <= target < 2<sup>32</sup> and  2 <= root < 64
* For all cases where 2<sup>64</sup>-100_000_000 <= target < 2<sup>64</sup> and  2 <= root < 64
* For 2<sup>34</sup> randomly selected values  2 <= target < 2<sup>64</sup> and  2 <= root < 64
* For 2<sup>35</sup> randomly selected values  2 <= target < 2<sup>64</sup> and  root == 2
* For 2<sup>35</sup> randomly selected values  2 <= target < 2<sup>64</sup> and  root == 3
