### ISSUE TITLE
Move `fuel-merkle` crate into `fuel-vm` repository

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#308]
According to https://github.com/FuelLabs/fuel-vm/pull/274, also include `fuel-merkle` into the `fuel-vm` repository.
Otherwise, we have a strange dependency graph:

`fuel-crypto`(`fuel-vm` repo) <- `fuel-merkle`(`fuel-merkle` repo) <- `fuel-storage`(`fuel-vm` repo)

**Comment by mitchmindtree** [comment]
Closed via #318
