### ISSUE TITLE
Fix nostd issue with getrandom in Wasmer

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#316]
The indexer is blocked on https://github.com/FuelLabs/fuel-indexer/issues/408 because of an invalid getrandom symbol coming from either fuel-vm repo or fuel-gql-client. Investigate whether random is being included somehow in our deps either on our end or on the indexer side (via feature flags).

**Comment by ra0x3** [comment]
@Voxelot 
- I sync'd w/ @segfault-magnet about this and I believe this is more so on the fuel-core team to fix? 
- @xgreenx I vaguely remember you mentioning that you were working on a potential fix for this? 
- Would be great to get this fixed for this milestone, as this has been an issue for some time.

**Comment by ra0x3** [comment]
- Also I _think_ this is blocking us adding `Tai64` support in https://github.com/FuelLabs/fuel-indexer/issues/898 for the explorer 
- Kinda the same thing as using `chrono` in an indexer - you _should_ be able to, but because we're stripping symbols, you can't

**Comment by xgreenx** [comment]
Because https://github.com/FuelLabs/fuel-vm/pull/582 is merged, it not more the problem of the `fuel-vm` repository. So I'm closing this issue=)

The next step is to finish https://github.com/FuelLabs/fuel-core/issues/1370, and after `fuel-rs` should patch their dependencies to be WASM compatible.
