### ISSUE TITLE
Data driven test suite for BMT Roots

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-vm#324]
- [ ] Each test file specifies the expected leaf data and expected root
- [ ] Test files are written in YAML syntax
- [ ] Test suite covers a range of roots, including empty root, single leaf root, and multiple leaf root
- [ ] `fuel-merkle` implements a test framework that reads in all data files
- [ ] Test suite is run automatically during CI

**Comment by xgreenx** [comment]
I think the current test coverage should be enough for now
