### ISSUE TITLE
Error when executing opcode: better error messages?

### ISSUE THREAD

**Issue by sezna** [FuelLabs/fuel-vm#33]
The UX around a failing contract call is rough. The same error, `Failed to execute opcode CALL(...)`, is thrown in all of the following cases:
1. not enough gas forwarded
2. too much gas forwarded 
3. Contract not in TX inputs
4. Contract in inputs not in TX outputs
5. probably more things

Would it be possible for the log message to tell the user a bit more about what went wrong?

**Comment by MitchTurner** [comment]
Currently, the error we get when there is a failed instruction will be something like this:
```
PanicInstruction(
        PanicInstruction {
            reason: OutOfGas,
            instruction: 272699456,
        },
    )
```
I think it would probably better to include the readible version of the `instruction`:
```
PanicInstruction(
        PanicInstruction {
            reason: OutOfGas,
            instruction: ADD { dst: 16, lhs: 17, rhs: 1 }
        },
    )
```
Either case isn't super useful to you if you're working from the Sway level, but would be from lower levels.

**Comment by MitchTurner** [comment]
Actually. It looks like this error gets swallowed. Will keep looking.

**Comment by MitchTurner** [comment]
We decided that the `PanicInstruction` we get currently probably fulfills this issue.

We decided against making it more readable because there have been no requests for that behavior, so YAGNI.

Closing.
