### ISSUE TITLE
Improve the Usability of Op codes by adding argument names to op codes

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-vm#349]
# Problem

The current Op codes use ra, rb, rc and rd as arguments, which can be confusing when using the ops.
It is hard to remember which argument is which when creating the op.

# Solution

Adding descriptive arguments such as sum, lhs, and rhs for `ADDI` to the Op codes will make them easier to understand and use.

# Example
```rust
impl_instructions! {
    "Adds two registers."
    0x10 ADDI addi [Sum: RegId, Lhs: RegId, Rhs: U12]
```
Which generates something like the following:
```rust
pub fn new(sum: RegId<u64>, lhs: RegId<u64>, rhs: Imm12<U12>) -> Self

pub fn sum(&self) -> RegId<u64>
pub fn lhs(&self) -> RegId<u64>
pub fn rhs(&self) -> Imm12<U12>
```
and a debug like:
```
ADDI { sum: RegId(16), lhs: RegId(17), rhs: U12(10) }
```

**Comment by Voxelot** [comment]
This seems like it's not critical for audits

**Comment by Dentosal** [comment]
Closeing this as completed. Feel free to open new issues for specific improvements.
