### ISSUE TITLE
Should `maturity` be `u32` or `Word`? `fuel-tx` says `Word`, spec says `u32`

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel-vm#357]
I've bumped into this a few times using the `fuel_tx` API downstream.

Here's an example in `fuel-tx`: https://github.com/FuelLabs/fuel-vm/blob/d9ed34c73e52281184a4e951bf3592264c1a6244/fuel-tx/src/transaction/types/script.rs#L35.

You can find the mentions in the spec here: https://fuellabs.github.io/fuel-specs/master/protocol/tx_format/transaction.html#transactionscript.

Should we change `fuel-tx` to comply with the spec? or change the spec to specify `maturity` is a `Word`?

**Comment by Voxelot** [comment]
we don't support block heights > 32bits, so this should probably be adjusted. My guess is this was done to simplify word padded serialization.
