### ISSUE TITLE
Make `SerializedSize` return const size

### ISSUE THREAD

**Issue by freesig** [FuelLabs/fuel-vm#368]
It'd be nice if we had a `SerializedSize` trait in fuel-types we could use to constrain `T` with here. Then we could ensure that the correct length is always used.

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-vm/pull/353#discussion_r1116419061_

**Comment by xgreenx** [comment]
Blocked by https://github.com/FuelLabs/fuel-vm/issues/443

**Comment by Dentosal** [comment]
Fixed in https://github.com/FuelLabs/fuel-vm/issues/443
