### ISSUE TITLE
Shield `unsafe` behind `optimized` feature

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#37]
Implement a new feature `optimized` to shield all unsafe usage.

When this feature is on, `unsafe` is allowed

When this feature is off, we should introduce `forbid_unsafe` in the root of the library:
`src/lib.rs`: `#![cfg_attr(not(feature = "optimized"), forbid(unsafe_code))]`

This means that all functions that use unsafe will have to be reimplemented with their safer (and potentially slower) counterparts

**Comment by Voxelot** [comment]
fixed by @freesig
