### ISSUE TITLE
Max transaction size

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#384]
Enforce an upper limit on the transaction size (17mb) which is validated whenever a transaction is checked.

AC:
- [ ] Maximum transaction size is described in the [transaction specification](https://github.com/FuelLabs/fuel-specs/blob/master/src/tx-format/transaction.md). The maximum transaction size is prescribed for all transaction types: `Create`, `Script`, and `Mint` - PR: https://github.com/FuelLabs/fuel-specs/pull/525
- [ ] Maximum transaction size is added to the consensus parameters - PR: https://github.com/FuelLabs/fuel-vm/pull/609
- [ ] Maximum transaction size is enforced during `check` for all transaction types: `Create`, `Script`, and `Mint`
  - Tests demonstrate that transactions with `size <= limit` are valid
  - Tests demonstrate that transactions with `size > limit` are invalid

**Comment by xgreenx** [comment]
Fixed with https://github.com/FuelLabs/fuel-vm/pull/609
