### ISSUE TITLE
Predicates don't get real values for BHEI, TIME, BHSH, CB

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#425]
Figure out if these actually need to be set properly

**Comment by xgreenx** [comment]
The support of these opcodes inside the predicate will make predicates non-deterministic and allow failure during block execution. So they should be disallowed in the predicate context.

The specification has already forbidden all contracts instructions inside of predicate.

<img width="1191" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/cec44945-c59e-4788-ab6b-b015f2c2ba2a">

The same as our code does. 

<img width="998" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/52d0caff-2832-4988-b508-7422d20644b0">
<img width="1012" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/b012c7bf-8066-439a-be0b-a98122d4bfb4">

So we can close this issue=)
