### ISSUE TITLE
Use 16kib leaf sizes when calculating code roots

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#434]
Spec change: https://github.com/FuelLabs/fuel-specs/pull/476

Improve the performance of calculating code roots by using a larger leaf size in the merkle tree to 16kib.

- Chunk bytecode and predicate code by 16kib chunks.
- Zero pad chunks out to the nearest multiple of 8 bytes if they are < 16kib. For example: if a predicate is only 500bytes, it should be padded out to 504 bytes no 16 kib.

**Comment by freesig** [comment]
@Voxelot What is the purpose of the padding?

**Comment by bvrooman** [comment]
> Zero pad chunks out to the nearest multiple of 8 bytes if they are < 16kib. For example: if a predicate is only 500bytes, it should be padded out to 508 bytes no 16 kib.

To be clear: 500 is already not divisible by 8; i.e. `500 mod 8 = 4`. Do you mean that 500 bytes would be zero padded to _504_ bytes, since `504 mod 8 = 0`?

**Comment by Voxelot** [comment]
> @Voxelot What is the purpose of the padding?

To preserve the original padding we used of 8 bytes. This is likely somewhat arbitrary though.
