### ISSUE TITLE
Add memory pages

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#452]
Instead of allocation `VM_MAX_RAM` on each `Interpreter`, dynamically allocate pages(for example, 16 KB) of memory and charge user only for those pages.

The tricky part is all memory range checks, increasing the stack size on `op::aloc`, loading of the contract, and so on. 
The maximum memory should still be `VM_MAX_RAM` and all previous rules should apply. 

During implementation decide: to use the same vector for heap and stack or have two separate memories.

The memory addressing should be dynamically translated into/from stack/heap.

**Comment by Dentosal** [comment]
This might have negative performance effects if we don't require alignment for some values. It would no longer be possible to return simple references to any data on memory, since any value could cross page boundary. Allowing reads from uninitialized memory complicates the issue even more.

We could use `Cow`-like type to work around this, but that would be both massive loss of ergonomics, and the worst case performance wouldn't improve at all. On the other hand, typically this just means copying some [u8; u32]  values on stack, which shouldn't be too slow.

**Comment by xgreenx** [comment]
Under the hood, it still can be the one slice of memory. We only need to grow the memory by 16KB chunks.

**Comment by Dentosal** [comment]
It cannot. At least stack and heap must be separate slices for this to actually reduce memory use. Then consider reading past the slice (e.g. past the stack boundary), for instance using the `LW` instruction. The returned data cannot be a reference, since there's no memory backing the region.

**Comment by xgreenx** [comment]
Two slices are what we discuss on the call. We only need to follow the rule that `heap.len + stack.len < MAX_MEMORY` to avoid infinite memory growth.

Hmm, maybe if someone tries to read from unallocated memory we need to return an error? Or we can return zero values

**Comment by Dentosal** [comment]
Uninitialized memory reads are allowed by the spec, and should return zeroes. But you cannot take a reference to unallocated memory in Rust, which gives us the potential performance issue I mentioned above.

**Comment by xgreenx** [comment]
I didn't get why we need a reference for `LW`. It seems we need only return a `0` in case memory is not initialized

**Comment by Dentosal** [comment]
Maybe LW was a bad example, but for instance `Address` is currently used in many places as `Address::from_bytes_ref_checked(...)` which would have to be changed to a copy instead of reference.

**Comment by Dentosal** [comment]
Well the function is still used, for instance here https://github.com/FuelLabs/fuel-vm/blob/e78648b70fe7df0c11cdddc93dbd7e57fca8f58a/fuel-tx/src/tests/offset.rs#L59

Moreover, almost all instances of `from_bytes_ref` are problematic as well.

In any case, we can simply change those to be copies. Should be cheap enough and most of them are probably optimized away anyway.

**Comment by Voxelot** [comment]
For gas pricing, we may need to consider whether there's an additional fee for allocating new memory pages. However we should get a rough idea from when we rerun the benchmarks whether this is a significant overhead that our linear per-byte cost model doesn't account for.

**Comment by Dentosal** [comment]
WIP spec PR: https://github.com/FuelLabs/fuel-specs/pull/489

**Comment by Voxelot** [comment]
Need to rebenchmark to confirm if this is a real issue with jemalloc enabled

**Comment by MitchTurner** [comment]
I see this on the Fuel Project Board, but I'm not sure that this is blocking testnet. Am I wrong?
