### ISSUE TITLE
Remove unchecked Word as usize casts

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-vm#474]
Currently the code does lots of `as usize` casts to allow indexing with register values. For instance all memory accesses need `usize` types. Since `Word as usize` casts lose precision on 32bit platforms, those should be properly checked. Clippy lint [`cast_possible_truncation`](https://rust-lang.github.io/rust-clippy/master/index.html#/cast_possible_truncation) can be used to find the problematic cases.

Alternatively we could restrict ourselves to 64bit platfroms only, at least temporarily.

**Comment by xgreenx** [comment]
@Dentosal Do we need to do something here or is that resolved?

**Comment by Dentosal** [comment]
I went through all all `as usize` casts outside tests, and they all seem reasonable. Closing as completed.
