### ISSUE TITLE
Standard values for `ConsensusParameters` and `GasCosts` shouldn't be tied to the `Default` impl

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-vm#515]
I don't think it is good to have the standard values tied to `Default`.

I think it would be more idiomatic to maybe have an explicit `fuel_standard()` function and have `default()` be zeroed out or removed completely.

The existence of `Default` implies (to me) that the fields on it will be modified, but even in the tests we are just using the standard values.

My actual recommendation would be to have the tests depend on their own set of parameters and have the tests written parametrically for whatever is used--thus giving coverage for changing parameters in the future (assuming they will change at some point). Then having the ACTUAL standard values exposed as its own repository, so it's decoupled completely from the VM that defines them.

**Comment by MitchTurner** [comment]
These issue is based on my limited exposure to the code, so there's a chance I'm missing some context.

**Comment by xgreenx** [comment]
Close in favor of https://github.com/FuelLabs/fuel-vm/issues/577
