### ISSUE TITLE
Merkle tree test vector format is not compatible between Rust and Solidity

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-vm#520]
From the audit report:

> ### Description
> The Rust and Solidity binary merkle tree is tested with yaml test vectors that are intended 
 to be uniform. However, the Rust tests contain an extra field, data, which contains the leaf 
 preimage while the Solidity test vector prepends the leaf hash to the proof set field. This 
 discrepancy causes failures if one copies the alternative implementation’s test vectors and 
 runs the test suite. Since these test vectors are considered the specification, it is important 
 they are correct and do not cause false positives which may motivate changes to the 
 implementation
> ### Recommendations 
> Short term, update the merkle tree verification tests such that the test vectors are uniform. 
 Long term, enforce that updates to the implementations and test vectors occur in parallel, 
 and consider performing differential fuzz testing between the Rust and Solidity 
 implementations.

**Comment by bvrooman** [comment]
The specific discrepancy between the Rust and Solidity test vectors highlighted in this report was addressed in [this PR](https://github.com/FuelLabs/fuel-vm/pull/502). This PR updated the algorithm for generating proofs to produce a format that conforms with what the Solidity version expects. This is also the format that is outlined in the spec now.
