### ISSUE TITLE
Make the fuel-vm no-std or WASM/RiscV compatible

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuel-vm#536]
## Abstract
We need to make the entire `fuel-vm` implementation **RiscV compatible** for fraud proving.

This would also allow for better browser, debugging and educational tools for the FuelVM.

### Currently Compatible
-  `fuel-asm`
- `fuel-types`
- `fuel-merkle`
- `fuel-storage`
- `fuel-crypto`

### Not Compatible
- `fuel-tx` (uses `fuel-crypto`)
- `fuel-vm` (uses `fuel-tx`)

Related:
https://github.com/FuelLabs/fuel-vm/issues/443
https://github.com/FuelLabs/fuel-vm/pull/533

**Comment by Dentosal** [comment]
Related: `getrandom` doesn't support freestanding riscv64, so we'll need [a fallback rng](https://docs.rs/getrandom/latest/getrandom/#unsupported-targets) or some other way to work around that.

**Comment by DefiCake** [comment]
Just reporting the state of compatibility with risc0 / riscV, fuel-crypto is compiling correctly now.

Currently, the build process complains about `fuel-tx`. 

```
error[E0277]: the trait bound `Transaction: fuel_tx::FormatValidityChecks` is not satisfied
   --> /Users/mad/fuel/vm/fuel-vm/src/checked_transaction.rs:577:22
    |
577 | impl IntoChecked for Transaction {
    |                      ^^^^^^^^^^^ the trait `fuel_tx::FormatValidityChecks` is not implemented for `Transaction`
    |
    = help: the following other types implement trait `fuel_tx::FormatValidityChecks`:
              fuel_tx::Create
              fuel_tx::Mint
              fuel_tx::Script
... 
```

Not very experienced in rs, but it looks to me as the `FormatValidityChecks` is only available under `std`:
```rs
#[cfg(feature = "std")]
impl FormatValidityChecks for Transaction {
...
```

**Comment by Dentosal** [comment]
This is almost achieved in https://github.com/FuelLabs/fuel-vm/issues/536, which makes the VM itself runnable under `no_std` conditions but still lacks some of the RiscV-specific stuff.

**Comment by xgreenx** [comment]
After https://danielmangum.com/posts/risc-v-bytes-rust-cross-compilation/, we are able to compile `fuel-vm` and `fuel-tx` into WASM and RiscV.

``` shell
cargo build --target wasm32-unknown-unknown --no-default-features -p fuel-tx --features alloc
cargo build --target wasm32-unknown-unknown --no-default-features -p fuel-vm --features alloc
cargo build --target riscv64imac-unknown-none-elf --no-default-features -p fuel-tx --features alloc
cargo build --target riscv64imac-unknown-none-elf --no-default-features -p fuel-vm --features alloc
```

Closing this issue=)
