### ISSUE TITLE
Define `default` values for `ConsensusParameters` and `InterpreterParams` only under test

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-vm#577]
Currently, `ConsensusParameters` defines a `default` constructor, which then constructs members using their respective `default` values or constructors. Because these consensus parameters are configured in the chainspec, using default values can create a discrepancy between what is configured and what is instantiated. This means the default values are not suitable for production use, and we must avoid using them in production code. 

The consequences of this could be that we have incorrect calculations, silent failures, or otherwise erroneous results if there is ever a discrepancy between the consensus parameters in-memory and the chainspec definition.  

Because `Default`, and similar constructors, is implemented outside of test, there is currently no reliable mechanism to prevent default values from being used in production code. Therefore, we want to introduce such a mechanism by making default values available only under test, guarded by a `cfg(test)` compile guard. Another option would be to introduce a new trait specifically for test defaults, e.g. `TestDefault` that is defined and implemented only under `cfg(test)`.

The same is true for other VM structs such as `InterpreterParams`.

AC:
- [ ] Implement `Default` for `ConsensusParameters` only under test
- [ ] Implement `Default` for `InterpreterParams` only under test

**Comment by MitchTurner** [comment]
Haha. Created a similar issue when I was in this code:
https://github.com/FuelLabs/fuel-vm/issues/515

**Comment by bvrooman** [comment]
> Haha. Created a similar issue when I was in this code: #515

Yep, sounds like an overlapping ticket. If we can consolidate on the action items and acceptance criteria and write them in your ticket, we could close this one as a duplicate.

**Comment by xgreenx** [comment]
@bvrooman @MitchTurner So, which ticket do we want to keep? It seems this ticket has more description

**Comment by xgreenx** [comment]
It was done in the #708
