### ISSUE TITLE
Add `wasm_bindgen` support for `fuel-tx`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#579]
Add `wasm_bindgen` support for `fuel-tx` crate as we did in https://github.com/FuelLabs/fuel-vm/pull/499.

Because we need to create wrappers for enums(they are not supported natively), we need to agree with the TS SDK team on which functionality they need. The most valuable are:
- Canonical serialization and deserialization of all types.
- Validation rules of `Check` transaction.

**Comment by Dentosal** [comment]
@FuelLabs/sdk-ts In addition to serialization/deserialization and validation rules, what other parts would be useful?
