### ISSUE TITLE
Feature request: jumpmap to visualize opcodes more easily

### ISSUE THREAD

**Issue by PaulRBerg** [FuelLabs/fuel-vm#584]
In REVM, they provide an opcode jump map:

https://github.com/bluealloy/revm/blob/26dc07dda5bf43d645b90ecaa986a3c4f6fe73b0/crates/interpreter/src/instructions/opcode.rs#L191

Which I find super helpful for visualizing opcodes, and which value slots are available and which aren't.

It would be great if the FuelVM implementation had something like this here:

https://github.com/FuelLabs/fuel-vm/blob/4340d14a6dc482aa197c0ee7d4f5920889949c6f/fuel-asm/src/lib.rs#L115

Alternatively, if you think that a jump map is overkill, adding comments with the unused slots would be helpful, too.

**Comment by Dentosal** [comment]
The similar operation is already achieved using `TryFrom<u8>`, which does the integer -> opcode conversion. The opcode names themselves can be obtained using `Debug` trait, although we could provide static strings instead if that's needed for performance reasons.

> Alternatively, if you think that a jump map is overkill, adding comments with the unused slots would be helpful, too.

I don't see any real reason to add comment per reserved opcode. The opcode list is in order, and has a double linebreak in any position with missing opcodes, making them easy to find.
