### ISSUE TITLE
Add TXO pointers to inputs

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#59]
Apply the changes proposed in https://github.com/FuelLabs/fuel-specs/pull/249

**Comment by adlerjohn** [comment]
Depends on https://github.com/FuelLabs/fuel-tx/issues/168

**Comment by Voxelot** [comment]
> and is malleated by the block producer as they're including transactions in a block

Is there actually any implementation work required of the VM? It seems like the behavior is managed by block producers/validators.

**Comment by adlerjohn** [comment]
Good point, it's external to the VM.

**Comment by An-tol** [comment]
gm
