### ISSUE TITLE
Charge transaction for signatures verification as part of `min_fee`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#599]
## Problem overview

ECR is the most expensive opcode in the VM (~1700 noops). However, we charge significantly less than that currently for verifying signatures used by coin or message inputs. This is partly because witness data is not chargeable. If we were to charge for signatures in witness data and also increase the GAS_PER_BYTE factor until the signature cost is adequately captured, this would disproportionately increase the cost of other bytes which should otherwise be cheap. We should have an independent charge which is based on the number of signatures a transaction has to verify, instead of warping the cost of bytes to cover it.

## Implementation details

The `check_signatures` method uses `is_predicate_owner_valid` and `recover_witness` under the hood(based on the type of inputs). They are the most expensive operations during the verification of the signatures.

For `recover_witness` we can use the the gas cost of the `ecr1` opcode. 

For `is_predicate_owner_valid`, it is more tricky because we use BMT under the hood + hashing function. For BMT we can either come up with a logarithmic formula or use hardcoded gas based on the worst possible scenario(the maximum size of the contract is 17 MB, while the predicate is less).

Both should affect the final `min_fee` in `TransactionFee::checked_from_values`. It may require some architectural modification into the `TransactionFee` structure because it requires inputs to calculate `min_fee`.

**Comment by bvrooman** [comment]
Closed by https://github.com/FuelLabs/fuel-vm/pull/613 and  https://github.com/FuelLabs/fuel-vm/pull/618
