### ISSUE TITLE
Charge `Create` transaction for `ContractId` calculate and validation

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#600]
## Overview

The validation of the `Create` transaction requires a `ContractId` calculation. It involves 2 BMT to calculate the code root hash and state root hash, plus a final hashing to produce `ContractId`.

These operations are not fast, and we should charge users for them.

```rust
        let contract_root = contract.root();
        let state_root = Contract::initial_state_root(storage_slots.iter());
        let contract_id = contract.id(salt, &contract_root, &state_root);
```

## Implementation details

The charging for predicate verification is similar to charging for a contract. So if the https://github.com/FuelLabs/fuel-vm/issues/599 is done, we can reuse the code from there. The only unsolved part is how to charge for the storage slots' BMT root calculation. We can come up with a formula or use the worst case with the `max_storage_slots` constant.

**Comment by bvrooman** [comment]
> It involves 2 BMT to calculate the code root hash and state root hash, plus a final hashing to produce ContractId.

Looking at the code, we have 1 BMT root for the code root, and 1 SMT root for the state root. State root is not a BMT so we will need to add another benchmark for this to calculate the dependent cost.

**Comment by bvrooman** [comment]
Completed by https://github.com/FuelLabs/fuel-vm/pull/618
