### ISSUE TITLE
Support SMT proofs generation

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#639]
The Fuel protocol uses sparse Merkle trees (SMTs) to generate "commitments" of data to a data set. Sparse Merkle trees are built upon sparse data - that is, data that is non-contiguous. This data can represented as a hash map, where data keys map to data values. As data is entered into the set, we build a tree of hashes (`sha256` hashes of the data and neighbour data) upwards.

Use cases for SMTs include contract storage slots.

A SMT proof is a way to prove that a specific chunk of data is included in a sparse set of data without having to share (for privacy, storage, or performance reasons) the entire set. This enables data-integrity checks in logarithmic time complexity.

By enabling SMT proofs, we can prove the existence or non-existence of data used in the Fuel protocol, including storage slots.

SMT proofs can be in a compressed or uncompressed format.

**Comment by MitchTurner** [comment]
Can we add some context to this issue?
