### ISSUE TITLE
Unable to access script bytecode

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/fuel-vm#649]
I'm trying to create scripts & predicates that check the script bytecode, however I haven't been able to successfully read that data.  For one thing, tx_script_length seems to be returning a length of 1.

I've created a repo to reproduce the issue:

https://github.com/dmihal/fuel-log-script

**Comment by xgreenx** [comment]
I assume you are using the wrong version of the `force`, which is incompatible with `fuel-core 0.22`. It works for me with `forc 0.48`. You are using `0.46.1`
<img width="1272" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/2da5de3b-7019-4e09-9cda-b3c2cb64d467">
<img width="922" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/1fae9551-fa39-4c32-a295-ce597d68c613">
