### ISSUE TITLE
Tracking: Malleable inputs for `Checked<Transaction>` type 

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#651]
Maybe move `fuel_core_executor::Executor::compute_inputs` to `Checked` or add a way of updating it.

<img width="1517" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/bd1e2619-a8d4-40c5-a360-472dbefd90b1">

**Comment by xgreenx** [comment]
Actually not, we decided to keep them malleable https://github.com/FuelLabs/fuel-specs/issues/542. But we still need to update the implementation

**Comment by Dentosal** [comment]
@xgreenx Do I understand correctly that the issue description is now outdated, and we just have to zero the malleable fields before execution?

**Comment by Dentosal** [comment]
> Yep=) We need to update the specification to reflect this change and update our codebase to zero all malleable fields(except witnesses)

So like this? https://github.com/FuelLabs/fuel-specs/pull/545 It feels weird to even have things like `InputCoin::tx_pointer` if that's zero-initialized.

**Comment by Dentosal** [comment]
@xgreenx Currently, `receipts_root` is updates in-memory after modifying receipts. Moreover, it's [specified to be](https://github.com/FuelLabs/fuel-specs/blob/master/src/tx-format/transaction.md):

> Note: when executing a script, receiptsRoot is initialized to zero.

> The receipts root receiptsRoot is the root of the [binary Merkle tree](https://github.com/FuelLabs/fuel-specs/blob/master/src/protocol/cryptographic-primitives.md#binary-merkle-tree) of receipts. If there are no receipts, its value is set to the root of the empty tree, i.e. `0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`.

This seems to conflict itself. What's the actual behavior we want here? Do we even need access to this value during execution?

**Comment by xgreenx** [comment]
> Note: when executing a script, receiptsRoot is initialized to zero.

By this phrase, we usually mean at the start of the execution of the transaction *something* should be zero=)

So, modifying it shouldn't affect the validity of the block(I mean the validator should receive the same result as a producer).

But, I don't think there is any use case for accessing the receipts root during the execution. Maybe somehow for the old fraud-proof model, but since we still need access to all old receipts to calculate the next receipt root, I don't think so. cc @Voxelot @dmihal 

Maybe it makes sense from a performance perspective only to do one root calculation at the end of the script execution. But it means we need to update the specification since it says that we need to update it each time:
> Append a receipt to the list of receipts, modifying `tx.receiptsRoot`:
