### ISSUE TITLE
Add a `setBreakpoints` method to the debugger

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/fuel-vm#656]
This function will replace all breakpoints with a given list of new breakpoints. [setBreakpoints](https://microsoft.github.io/debug-adapter-protocol//specification.html#Requests_SetBreakpoints)  is part of DAP. Having this exposed at the Interpreter level will make the code nicer.

**Comment by Dentosal** [comment]
Done! The requested method is called `overwrite_breakpoints` and will be available in the next fuel-vm version.
