### ISSUE TITLE
Add pkcs#11 support to fuel-crypto

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#662]
In order to support remote hsm's we should consider adding pkcs#11 support to fuel-crypto. This would allow fuel-crypto to be integrated with cloudhsm or other key providers: https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-key-types.html

**Comment by MitchTurner** [comment]
We are going to close this in favor of having `aws` tools inside of `fuel-crypto`.

The `pkcs` libraries are a little too generic for our usecase and they don't support `no-std`, unfortunately, which would make it hard to integrate into our state transition function.

Closing in favor of: #865
