### ISSUE TITLE
Gas fee issues

### ISSUE THREAD

**Issue by Starrr23** [FuelLabs/fuel-vm#677]
Utilizing data availability protocols such as 
![Uploading 20240218_074150.jpg…]()
Celestia presents a promising solution to alleviate the burden of gas fees associated with scrolling. These protocols are designed to optimize the storage and accessibility of data on decentralized networks, offering a decentralized and efficient alternative to traditional methods. By implementing these protocols, users can store data more efficiently and access it seamlessly, reducing the computational resources required for tasks like scrolling through content. This, in turn, translates to a reduction in gas fees, as fewer computational resources are needed to execute transactions on the blockchain. Moreover, the decentralized nature of these protocols enhances data security and resilience, further bolstering the overall efficiency and reliability of the system. Embracing data availability protocols represents a significant step towards addressing the scalability and cost challenges associated with blockchain-based applications, paving the way for a more sustainable and accessible decentralized ecosystem. To sum it up, I believe that if we utilise data availability protocols mentioned above, it will help  gas fee on fuel 

Thank you for taking this into consideration!

**Comment by xgreenx** [comment]
Hello, thank you for creating the issue. We already have plans regarding DA layers. I'm closing this issue since it is not fully ready, maybe AI generated, and DA is already in our roadmap.
