### ISSUE TITLE
Bundle Tx execution on SubState with DB binding

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-vm#68]
When creating a new block or when importing a block from the network we need to have the ability to execute all transactions in some temporary state. Check if outputs/storages/hashes/merkletriees matches what is given, or in case of a new block, they need to be created. And then apply that temporary state to the database, or for new block send it to consensus for signing.

Maybe call it SubState? (name pending)

SubState should have its own changed state and in case if a state item (Storage/utxo) is not found it should have the ability to fetch it from DB.
It should probably contain the malleable list of executed transactions.

**Comment by rakita** [comment]
@Voxelot here is a little bit more explanation on the topic: https://github.com/FuelLabs/fuel-vm/blob/bundler/README.md
It is written in more strict language as "it has" in contrast to more relaxed as "it should have"/"it could have", but it is still WIP.

**Comment by Voxelot** [comment]
This is largely duplicative of the transactional database features and block executor in fuel-core. The VM is not the place where we'll handle complicated state management of UTXO's etc for the time being.
