### ISSUE TITLE
Use methods from `StorageRead` trait in the LDC and copy code opcodes

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#681]
We need to remove `storage_contract` method and update all places to use `StorageRead::read` method instead.

<img width="1233" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/74b8f6a7-b10a-4e9a-895c-e1e03cb853b7">

**Comment by acerone85** [comment]
Tentatively assigning myself
