### ISSUE TITLE
Update `Transaction` type to represent forcibly included transactions

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#693]
Update `Transaction` type to represent forcibly included transactions that can be used for fraud proofs to provide that transact was included(successfully or unsuccessfully)

**Comment by Voxelot** [comment]
we probably don't need this task

**Comment by Voxelot** [comment]
As an alternative, I think we should just emit events from the executor for failed forced transactions which we can use to update the tx_status table off-chain.

**Comment by xgreenx** [comment]
We decided to not affect the `Transaction` since it is only relevant for the GraphQL/Frontend and it can addressed off-chain.
