### ISSUE TITLE
Extract cryptography-related helpers into an external crate

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuel-vm#71]
Downstream crates, such as `fuels-rs` started to rely on cryptographic functions that live under `fuel-vm` such as `secp256k1_sign_compact_recoverable()` and `secp256k1_sign_compact_recover()` in `scr/crypto.rs`.

Since they're not exclusive to the FuelVM and will be used in other places, to avoid (1) implementation of cryptographic functions and (2) depending on the FuelVM for those, we should extract these and other cryptographic-related functions into another, lighter weight crate.

**Comment by Voxelot** [comment]
cc @adlerjohn should we make a new fuel-crypto repo?

**Comment by adlerjohn** [comment]
Not a bad idea.

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-crypto
