### ISSUE TITLE
The `fuel_merkle::binary::verify` almost ignores the `num_leaves`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#716]
The test below returns `Ok` while it should fail.
 
<img width="1202" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/d635d4ee-8011-4b71-b20b-06fc5233b3b2">

The test is added [here](https://github.com/FuelLabs/fuel-vm/pull/714/files#diff-0a832a3dab862c6b60a2535e3948affb771bfca192c62ddb6ce4456f3e63ecd2).

**Comment by xgreenx** [comment]
Maybe we need to add [this](https://github.com/FuelLabs/fuel-merkle-sol/blob/e34d80754e52e28b03909bf61c1c038bf5aa6207/contracts/tree/binary/BinaryMerkleTreeUtils.sol#L74) check as well

**Comment by bvrooman** [comment]
> Maybe we need to add [this](https://github.com/FuelLabs/fuel-merkle-sol/blob/e34d80754e52e28b03909bf61c1c038bf5aa6207/contracts/tree/binary/BinaryMerkleTreeUtils.sol#L74) check as well

I implemented the same check in `fuel-merkle` and incorporated it in the `verify` function. However, the tests still failed in this way. 

After a while trying to identify any differences in code, I decided I would apply the same test case against the `fuel-merkle-sol` implementation. It turns out that the `fuel-merkle-sol` implementation also suffers from this issue, and the test cases fail.

**Comment by bvrooman** [comment]
I think this may not be a "solvable" problem.

From the perspective of the `verify` function, there may actually be no difference in the "shape" of two different proofs. For example, a tree with 3 leaves will generate the same "shape" of proof as a tree with 4 leaves. In both cases, the tree has a height of 2, and therefore 2 items in the proof set. They will only differ by hashes. Unfortunately, there is no way (that I can think of?) to determine from the hashes alone what the shape of the original tree was.

This means that a tree with `num_leaves` in the range (`2^n`, `2^(n+1)`] will produce proofs with the same number of items in the proof set, and it's not possible to determine from the proof set alone if the number of leaves is accurate. During verification, the number of leaves is used only as a hint to help the algorithm know how to combine items in the proof set when reconstructing the root.
