### ISSUE TITLE
Non-padded `Call.code_size`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#763]
`Call` does not [include](https://github.com/FuelLabs/fuel-vm/blob/795d2eebfda2e2ccc407a02bebefa975e1e19b6d/fuel-vm/src/interpreter/flow.rs#L674) the padding after code as part of `CallFrame.code_size`. This may eventually lead to incorrect `code_size` calculations within the ldc opcode.

**Comment by Voxelot** [comment]
fixed by: https://github.com/FuelLabs/fuel-vm/pull/736
