### ISSUE TITLE
Handle error in the cases with `MaybeUninit`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#811]
During decoding arrays, we use `MaybeUninit`.  If we get an error during this process, we will have a memory leak since `MaybeUninit` doesn't call drop on internal objects.

<img width="730" alt="image" src="https://github.com/user-attachments/assets/fc6d1a11-0995-4c2d-8230-4952baf009a5">

**Comment by acerone85** [comment]
I can have a look at this one while I am blocked on other issues. 

Is this the only function where we need to handle errors on partial initialization?
