### ISSUE TITLE
Externalize Validity Checks

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#82]
Currently the VM performs several validity checks on a transaction in the init/run methods. This includes things like:

- Checking the input vs output amounts
- Verifying predicates (currently only done for create txs)
- Verifying contract outputs have corresponding inputs

Along with many other checks. Since these are internalized to the VM, the only way for the client to perform all these internal validations is to dry-run each tx. While feasible, it may be better if VM provided an interface for purely validating txs, which could be reused in many places such as both tx pool submission or block execution. This would make it easier to prevent blocks with invalid / unspendable utxos from ever being constructed.

**Comment by vlopes11** [comment]
We need to carefully guarantee that every transaction execute is preceded by a validation because an invalid transaction execution attempt might result in a panic.

The VM performs the validation set in `init` to assure we have that.

One alternative is to create a `unsafe fn transact_unchecked(Transaction)` that will not perform the validity check, trusting its caller will perform that under a different context

**Comment by rakita** [comment]
To say this in a different format, we have two types of checks on tx:
1. Standalone checks: this can be parallelized and done before block execution and txpool inclusion.
2. Dependency checks: needs other UTXO to validate tx, done in block execution.

All other things fall in their place around this.

**Comment by Voxelot** [comment]
Rather than an unsafe method to run transactions, what if we utilized a special new-type wrapper for transactions that have been validated by the VM? Something like `struct VmCheckedTransaction(Transaction);` We could make it so the only way to construct these wrapped transactions is by running the validation method of the VM. Then the interpreter init methods could be modified to only accept these checked transactions.

This way, we can flexibly verify transactions when needed and avoid redundancy.

**Comment by Voxelot** [comment]
@vlopes11 brought up a good point that the VM shouldn't have to be responsible for validating the transaction at all, and we can move all these checks to fuel-tx. This would definitely be a cleaner approach I think, so I'm going to focus on pivoting the concept of `CheckedTransaction`'s over to the fuel-tx domain instead.
