### ISSUE TITLE
Clarify Word Type Usage in ContractsAssets

### ISSUE THREAD

**Issue by almachzumi** [FuelLabs/fuel-vm#827]
Data Type Clarity: The `contracts_assets.rs` file defines the `ContractsAssets` structure that uses Word as the data type to store asset balances. However, it is unclear whether Word in this context refers to a 32-bit or 64-bit data type.

are there any special considerations in choosing `double_key`! and if there are other alternatives that may be more efficient or easier to understand

![contracts_assets rs](https://github.com/user-attachments/assets/0e3f79f8-49d5-4bee-b322-f0a169b87149)

**Comment by xgreenx** [comment]
> Data Type Clarity: The contracts_assets.rs file defines the ContractsAssets structure that uses Word as the data type to store asset balances. However, it is unclear whether Word in this context refers to a 32-bit or 64-bit data type.

The `Word` is a type defined in the `fuel-types` crate. It is alias for the `u64`.

> are there any special considerations in choosing double_key! and if there are other alternatives that may be more efficient or easier to understand

The table's key is a composition of two types - `ContractId` and `Assetid`. The mentioned macro helps to define this key type.
