### ISSUE TITLE
`SecretKey::default` is an invalid secret key

### ISSUE THREAD

**Issue by segfault-magnet** [FuelLabs/fuel-vm#830]
Reproduction
```rust
        let default_secret_key = SecretKey::default();
        let message = Message::from_bytes([0; 32]);

        // panics with:
        // SecretKey is guaranteed to be valid: Error
        Signature::sign(&default_secret_key, &message);

```

**Comment by rymnc** [comment]
looking into this. can reproduce.

**Comment by rymnc** [comment]
you should use the `random` feature of `fuel-vm` and instead use `SecretKey::random()` to generate an arbitrary secret key. If you wish for some determinism, then perhaps try using a non-zero static key :)
