### ISSUE TITLE
ScriptResult inconsistent with RVRT opcode and ProgramState

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#88]
When a contract or script uses the revert opcode, the interpreter returns the program state as `Revert(_)`. However, the script result receipt returns as successful (0 / RESERV00).

The expected behavior would be that the script result would return the RVRT in the instruction result and use PanicReason::Revert.

The docs for panic reason say:
```
/// Panic reason representation for the interpreter.
pub enum PanicReason {
    /// Found `RVRT` instruction.
    Revert = 0x01,
```

However, when I run a script that reverts, the panic reason is returned as `RESERV00`.

repro:
```
#[test]
fn revert_returns_value() {
    let script = vec![Opcode::RVRT(REG_ONE)];
    let result = TestBuilder::new(2322).script(script).execute();
    eprintln!("{:#?}", result);
}
```

**Comment by adlerjohn** [comment]
Wait, a revert is not a panic.

**Comment by Voxelot** [comment]
So what is the expected script result after a RVRT opcode is processed? Success / 0?

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-specs/blob/38d259f1a239908c01f1471d8efe8c9e5a58e80f/specs/vm/opcodes.md#rvrt-revert

> If current context is external, append an additional receipt to the list of receipts, modifying tx.receiptsRoot:
> result | uint64 | 0

So, success? Which makes sense because it's not a panic.

**Comment by Voxelot** [comment]
LInking to https://github.com/FuelLabs/fuel-specs/issues/289 for context

**Comment by Voxelot** [comment]
fixed by: https://github.com/FuelLabs/fuel-tx/pull/99
